version: '3.9'

services:
  db:
    image: mysql:5.7
    container_name: wp_db-loverFlover
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loverFlover
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wp_site-loverFlover
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      TZ: "Europe/Kyiv"
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: loverFlover
      WORDPRESS_DEBUG: 1
    volumes:
      - ./wordpress:/var/www/html
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/90-uploads.ini:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp_pma-loverFlover
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: wpuser
      PMA_PASSWORD: wppassword

volumes:
  db_data:
